# Generated by Django 5.1.6 on 2025-03-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='pin',
        ),
    ]
