# Generated by Django 5.1.6 on 2025-03-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_baseuser_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='username',
        ),
    ]
