# Generated by Django 5.1.6 on 2025-03-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_baseuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseUser',
        ),
    ]
