# Generated by Django 5.1.6 on 2025-03-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_email_remove_user_username_user_pin_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
