# Generated by Django 5.1.6 on 2025-03-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='builders/')),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='floor_plans/')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255)),
                ('phone', models.CharField(default=None, max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nearby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='nearby_icon/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rough_price_range', models.CharField(help_text='Example: 50L - 1.5Cr', max_length=255)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('project_size', models.CharField(help_text='Example: 7.74 Acres', max_length=255)),
                ('possession_start_date', models.DateField(blank=True, null=True)),
                ('avg_price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rera_id', models.CharField(blank=True, help_text='RERA Registration ID', max_length=255, null=True)),
                ('configurations', models.CharField(blank=True, help_text='2 & 3 bhk bungalows', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('featured_project', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=50)),
                ('carpet_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('super_built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('listing_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('is_project_based', models.BooleanField(default=False, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent'), ('lease', 'Lease'), ('invest', 'Invest')], max_length=10, null=True)),
                ('rate_type', models.CharField(choices=[('direct', 'Direct'), ('sqfeet', 'Sq. Feet')], default='direct', max_length=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_area', models.CharField(blank=True, max_length=255, null=True)),
                ('parking_area', models.CharField(blank=True, max_length=255, null=True)),
                ('terrace_area', models.CharField(blank=True, max_length=255, null=True)),
                ('dimension_size', models.CharField(blank=True, help_text='Example: 11x30', max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('get_direction', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented')], default='available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_subcategory/')),
                ('homefeed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(help_text='Hex color code (e.g., #FF5733)', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.amenitycategory')),
            ],
        ),
    ]
